// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggzwvjyioqkljbnzupaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnend2anlpb3FrbGpibnp1cGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTk0NzQsImV4cCI6MjA3MDM5NTQ3NH0.M6wd9MTDvNdz622n4ASYjdwvro3wNY1eDg_YxmjUDLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});